title: Zhe Fei (费哲) # your name (or website title) here
logo: "/images/feizhephoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Assistant Professor at UC Riverside, Statistics Department
  <br><br>
  <a href="https://www.dropbox.com/s/t5x3i6ysq3hjki8/CV_ZheFei_public.pdf?dl=0">CV</a>
  <br><br>
  <a href="https://ph.ucla.edu/faculty/fei">Webpage at UCLA</a> 
  <br><br>
  <a href="https://sites.google.com/view/feizhepku">Research</a> 
  <br><br>
  <a href="https://sites.google.com/view/feizhepku">Teaching</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
